### ISSUE TITLE
Asking for a story which contains an inexisting resource file will produce an ENOENT error

### ISSUE THREAD

**Issue by robindemourat** [medialab/quinoa-server#32]
Example : https://fonio.medialab.sciences-po.fr/allen/quinoa/api/stories/656806a6-7cc0-49dc-a437-d675c26a5d06?edit=false&format=json

Returns the message :

```
{"message":"ENOENT: no such file or directory, open '/quinoa-server/data/stories/656806a6-7cc0-49dc-a437-d675c26a5d06/resources/014012b6-2b71-4f14-b6f4-c9ca08659d7f/014012b6-2b71-4f14-b6f4-c9ca08659d7f.png'"}
```

**Comment by robindemourat** [comment]
It should instead return an empty `data` property faulty resource. When we have more time we should also investigate how it could happen (image file is removed but resource still exists in resource's JSON)

**Comment by mydu** [comment]
Resolution: 
* when import story, to create image/table resource, if no data(image/json) in story.json, create empty folder under resource folder by resource id
* when export story, if no resource file on server(unknown deletion issue), use filePath as the data source
